image: ghcr.io/miroling/design-relational-databases:main

tasks:
  - command: |
      eval $(gp env -e)
      jupyter lab --JupyterApp.config_file=jupyter_notebook_config.py

ports:
  - port: 8888
    visibility: public

vscode:
  extensions:
    - shd101wyy.markdown-preview-enhanced
    - codezombiech.gitignore
    - shivaprasanth.code-notebook-plantuml
    - ms-toolsai.jupyter
    - ms-python.python
    - ms-toolsai.jupyter-keymap
    - ms-toolsai.vscode-jupyter-cell-tags
    - ms-toolsai.vscode-jupyter-slideshow
    - ms-toolsai.jupyter-renderers
    - chrisjsewell.myst-tml-syntax
    - streetsidesoftware.code-spell-checker-ukrainian
