#######################################################################################
# A default configuration that will be loaded for all jupyter books
# See the documentation for help and more options: 
# https://jupyterbook.org/customize/config.html

#######################################################################################
# Book settings
title                       : Проектування реляційних баз даних  # The title of the book. Will be placed in the left navbar.
author                      : ""  # The author of the book
copyright                   : "2023"  # Copyright year to be placed in the footer

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: auto

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: book.tex


sphinx:
  config:
    language: uk
    html_context:
      default_mode: "light"
      github_user: "Miroling"
      github_repo: "design-relational-databases"
      github_version: "main"
      github_url: "https://github.com"
      use_repository_button:
    html_show_copyright: false
    html_theme_options: 
      use_edit_page_button: true
      use_repository_button: true
      logo:
        image_light: img/logo-color.png
        image_dark: img/logo-white.png
      extra_footer: |
        <p xmlns:cc="http://creativecommons.org/ns#" xmlns:dct="http://purl.org/dc/terms/"><a property="dct:title" rel="cc:attributionURL" href="https://miroling.github.io/design-relational-databases/">Проектування реляційних баз даних</a> by <a rel="cc:attributionURL dct:creator" property="cc:attributionName" href="https://taras.pro">Омеляненко Тарас</a> is licensed under <a href="http://creativecommons.org/licenses/by/4.0/?ref=chooser-v1" target="_blank" rel="license noopener noreferrer" style="display:inline-block;">Attribution 4.0 International<img style="height:22px!important;margin-left:3px;vertical-align:text-bottom;" src="https://mirrors.creativecommons.org/presskit/icons/cc.svg?ref=chooser-v1"><img style="height:22px!important;margin-left:3px;vertical-align:text-bottom;" src="https://mirrors.creativecommons.org/presskit/icons/by.svg?ref=chooser-v1"></a></p>