version: '3'

services:
  jupyter:
    build:
      dockerfile: .gitpod.Dockerfile
    ports:
      - 3306:3306
      - 8888:8888
    volumes:
      - ./:/home/gitpod/workspace
#    working_dir: /home/gitpod/workspace
#    command: "jupyter lab --ip 0.0.0.0"