version: '3'

services:
  jupyter:
    build:
      dockerfile: .gitpod.Dockerfile
    ports:
      - 3306:3306
      - 33060:33060
      - 8888:8888
    volumes:
      - ./:/workspace/design-relational-databases
    working_dir: /workspace/design-relational-databases
    command: "jupyter lab --ip 0.0.0.0"